version: '3'

services:
  boilerplate-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: boilerplate-service
    container_name: boilerplate
    restart: unless-stopped
    ports:
      - 8081:${PORT}
    volumes:
      - /usr/src/app/node_modules
      - ./:/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: boilerplate-mongodb
    ports:
      - 27017:27017  